default_view:
  view: yes
  entities:
    - group.inside
    - group.garage
    - group.rhasspy

garage:
  name: Garage
  entities:
    - switch.garage_light
    - binary_sensor.garage_door

inside:
  name: Inside
  entities:
    - switch.living_room_lamp
    - sensor.temperature

rhasspy:
  name: "rhasspy"
  entities:
    - stt_pocketsphinx.pocketsphinx
    - sensor.last_text
