# Automatically listen for the hotword when Home Assistant starts.
- alias: "start hotword"
  trigger:
    platform: homeassistant
    event: start
  action:
    service: hotword_snowboy.listen

# Play a sound when the hotword is detected.
# Start listening for a command.
- alias: "hotword -> speech to text"
  trigger:
    platform: event
    event_type: hotword_detected
  action:
    - service: wav_aplay.play_wav
      data:
        filename: $RHASSPY_ASSISTANT/etc/wav/wakeup.wav
    - service: stt_pocketsphinx.listen

# Play a sound when recording of a command has finished.
- alias: "speech to text working"
  trigger:
    platform: event
    event_type: speech_recorded
  action:
    - service: wav_aplay.play_wav
      data:
        filename: $RHASSPY_ASSISTANT/etc/wav/command_recorded.wav
